# Generated by Django 4.1.7 on 2023-05-10 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dates',
        ),
        migrations.AddField(
            model_name='flights',
            name='arrival_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='flights',
            name='departure_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
