# Generated by Django 4.1.7 on 2023-05-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_delete_dates_flights_arrival_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='code',
            field=models.CharField(default='00000', max_length=5),
        ),
    ]
