# Generated by Django 4.1.7 on 2023-05-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_flights_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flights',
            name='id',
        ),
        migrations.AlterField(
            model_name='flights',
            name='code',
            field=models.CharField(default='00000', max_length=5, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Passangers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('flights', models.ManyToManyField(blank=True, related_name='passanger', to='web.flights')),
            ],
        ),
    ]
